export const GET_ALL_TASKS_SUCCESS = 'GET_ALL_TASKS_SUCCESS';
export const CREATE_TASK_REQUEST_SUCCESS = 'CREATE_TASK_REQUEST_SUCCESS';
export const UPDATE_TASK_REQUEST_SUCCESS = 'UPDATE_TASK_REQUEST_SUCCESS';
export const DELETE_TASK_REQUEST_SUCCESS = 'DELETE_TASK_REQUEST_SUCCESS';
